### ISSUE TITLE
References

### ISSUE THREAD

**Issue by yuw444** [maumneto/TemplateBeamerUFC#3]
Hi,

Again, it's me. I'm not sure if you have noticed that there are two "reference" 's on the top of the automatic navigation panel. Could you advise on that as well?

Thanks

**Comment by yuw444** [comment]
Never mind on this, I just deleted the `\section{Reference}`, it fixed the problem.

**Comment by maumneto** [comment]
Ok. This is an error in this template version. I will fix it in the next version! Thank you a lot!
